relatorPrefixes = {"abridger": "relators:abr;",
                   "actor": "relators:act;",
                   "adapter": "relators:adp;",
                   "addressee": "relators:rcp;",
                   "analyst": "relators:anl;",
                   "animator": "relators:anm;",
                   "annotator": "relators:ann;",
                   "applicant": "relators:app;",
                   "architect": "relators:arc;",
                   "arranger": "relators:arr;",
                   "art copyist": "relators:acp;",
                   "art director": "relators:adi;",
                   "artist": "relators:art;",
                   "artistic director": "relators:ard;",
                   "assignee": "relators:asg;",
                   "associated name": "relators:asn;",
                   "attributed name": "relators:att;",
                   "auctioneer": "relators:auc;",
                   "author": "relators:aut;",
                   "author in quotations or text abstracts": "relators:aqt;",
                   "author of afterword, colophon, etc.": "relators:aft;",
                   "author of dialog": "relators:aud;",
                   "author of introduction, etc.": "relators:aui;",
                   "autographer": "relators:ato;",
                   "bibliographic antecedent": "relators:ant;",
                   "binder": "relators:bnd;",
                   "binding designer": "relators:bdd;",
                   "blurb writer": "relators:blw;",
                   "book designer": "relators:bkd;",
                   "book producer": "relators:bkp;",
                   "bookjacket designer": "relators:bjd;",
                   "bookplate designer": "relators:bpd;",
                   "bookseller": "relators:bsl;",
                   "braille embosser": "relators:brl;",
                   "broadcaster": "relators:brd;",
                   "calligrapher": "relators:cll;",
                   "cartographer": "relators:ctg;",
                   "caster": "relators:cas;",
                   "censor": "relators:cns;",
                   "choreographer": "relators:chr;",
                   "cinematographer": "relators:cng;",
                   "client": "relators:cli;",
                   "collection registrar": "relators:cor;",
                   "collector": "relators:col;",
                   "collotyper": "relators:clt;",
                   "colorist": "relators:clr;",
                   "commentator": "relators:cmm;",
                   "commentator for written text": "relators:cwt;",
                   "compiler": "relators:com;",
                   "complainant": "relators:cpl;",
                   "complainant-appellant": "relators:cpt;",
                   "composer": "relators:cmp;",
                   "compositor": "relators:cmt;",
                   "conceptor": "relators:ccp;",
                   "conductor": "relators:cnd;",
                   "conservator": "relators:con;",
                   "consultant": "relators:csl;",
                   "consultant to a project": "relators:csp;",
                   "contestant": "relators:cos;",
                   "contestant-appellant": "relators:cot;",
                   "contestant-appellee": "relators:coe;",
                   "contractor": "relators:ctr;",
                   "contributor": "relators:ctb;",
                   "copyright claimant": "relators:cpc;",
                   "copyright holder": "relators:cph;",
                   "corrector": "relators:crr;",
                   "correspondent": "relators:crp;",
                   "costume designer": "relators:cst;",
                   "court governed": "relators:cou;",
                   "court reporter": "relators:crt;",
                   "cover designer": "relators:cov;",
                   "creator": "relators:cre;",
                   "curator": "relators:cur;",
                   "dancer": "relators:dnc;",
                   "data contributor": "relators:dtc;",
                   "data manager": "relators:dtm;",
                   "dedicatee": "relators:dte;",
                   "dedicator": "relators:dto;",
                   "degree granting institution": "relators:dgg;",
                   "degree supervisor": "relators:dgs;",
                   "delineator": "relators:dln;",
                   "depicted": "relators:dpc;",
                   "depositor": "relators:dpt;",
                   "designer": "relators:dsr;",
                   "director": "relators:drt;",
                   "dissertant": "relators:dis;",
                   "distribution place": "relators:dbp;",
                   "distributor": "relators:dst;",
                   "donor": "relators:dnr;",
                   "draftsman": "relators:drm;",
                   "dubious author": "relators:dub;",
                   "editor": "relators:edt;",
                   "editor of compilation": "relators:edc;",
                   "editor of moving image work": "relators:edm;",
                   "electrician": "relators:elg;",
                   "electrotyper": "relators:elt;",
                   "enacting jurisdiction": "relators:enj;",
                   "engineer": "relators:eng;",
                   "engraver": "relators:egr;",
                   "etcher": "relators:etr;",
                   "event place": "relators:evp;",
                   "expert": "relators:exp;",
                   "facsimilist": "relators:fac;",
                   "field director": "relators:fld;",
                   "film director": "relators:fmd;",
                   "film distributor": "relators:fds;",
                   "film editor": "relators:flm;",
                   "film producer": "relators:fmp;",
                   "filmmaker": "relators:fmk;",
                   "first party": "relators:fpy;",
                   "forger": "relators:frg;",
                   "former owner": "relators:fmo;",
                   "funder": "relators:fnd;",
                   "geographic information specialist": "relators:gis;",
                   "honoree": "relators:hnr;",
                   "host": "relators:hst;",
                   "host institution": "relators:his;",
                   "illuminator": "relators:ilu;",
                   "illustrator": "relators:ill;",
                   "inscriber": "relators:ins;",
                   "instrumentalist": "relators:itr;",
                   "interviewee": "relators:ive;",
                   "interviewer": "relators:ivr;",
                   "inventor": "relators:inv;",
                   "issuing body": "relators:isb;",
                   "jurisdiction governed": "relators:jug;",
                   "laboratory": "relators:lbr;",
                   "laboratory director": "relators:ldr;",
                   "landscape architect": "relators:lsa;",
                   "lead": "relators:led;",
                   "lender": "relators:len;",
                   "librettist": "relators:lbt;",
                   "licensee": "relators:lse;",
                   "licensor": "relators:lso;",
                   "lighting designer": "relators:lgd;",
                   "lithographer": "relators:ltg;",
                   "lyricist": "relators:lyr;",
                   "manufacture place": "relators:mfp;",
                   "manufacturer": "relators:mfr;",
                   "marbler": "relators:mrb;",
                   "markup editor": "relators:mrk;",
                   "medium": "relators:med;",
                   "metadata contact": "relators:mdc;",
                   "metal-engraver": "relators:mte;",
                   "minute taker": "relators:mtk;",
                   "moderator": "relators:mod;",
                   "monitor": "relators:mon;",
                   "music copyist": "relators:mcp;",
                   "musical director": "relators:msd;",
                   "musician": "relators:mus;",
                   "narrator": "relators:nrt;",
                   "onscreen presenter": "relators:osp;",
                   "opponent": "relators:opn;",
                   "organizer": "relators:orm;",
                   "originator": "relators:org;",
                   "other": "relators:oth;",
                   "owner": "relators:own;",
                   "panelist": "relators:pan;",
                   "papermaker": "relators:ppm;",
                   "patent applicant": "relators:pta;",
                   "patent holder": "relators:pth;",
                   "patron": "relators:pat;",
                   "performer": "relators:prf;",
                   "permitting agency": "relators:pma;",
                   "photographer": "relators:pht;",
                   "platemaker": "relators:plt;",
                   "praeses": "relators:pra;",
                   "presenter": "relators:pre;",
                   "printer": "relators:prt;",
                   "printer of plates": "relators:pop;",
                   "printmaker": "relators:prm;",
                   "process contact": "relators:prc;",
                   "producer": "relators:pro;",
                   "production company": "relators:prn;",
                   "production designer": "relators:prs;",
                   "production manager": "relators:pmn;",
                   "production personnel": "relators:prd;",
                   "production place": "relators:prp;",
                   "programmer": "relators:prg;",
                   "project director": "relators:pdr;",
                   "proofreader": "relators:pfr;",
                   "provider": "relators:prv;",
                   "publication place": "relators:pup;",
                   "publishing director": "relators:pbd;",
                   "puppeteer": "relators:ppt;",
                   "radio director": "relators:rdd;",
                   "radio producer": "relators:rpc;",
                   "recording engineer": "relators:rce;",
                   "recordist": "relators:rcd;",
                   "redaktor": "relators:red;",
                   "renderer": "relators:ren;",
                   "reporter": "relators:rpt;",
                   "repository": "relators:rps;",
                   "research team head": "relators:rth;",
                   "research team member": "relators:rtm;",
                   "researcher": "relators:res;",
                   "respondent": "relators:rsp;",
                   "responsible party": "relators:rpy;",
                   "restager": "relators:rsg;",
                   "restorationist": "relators:rsr;",
                   "reviewer": "relators:rev;",
                   "rubricator": "relators:rbr;",
                   "scenarist": "relators:sce;",
                   "scientific advisor": "relators:sad;",
                   "screenwriter": "relators:aus;",
                   "scribe": "relators:scr;",
                   "sculptor": "relators:scl;",
                   "second party": "relators:spy;",
                   "secretary": "relators:sec;",
                   "seller": "relators:sll;",
                   "set designer": "relators:std;",
                   "setting": "relators:stg;",
                   "signer": "relators:sgn;",
                   "singer": "relators:sng;",
                   "sound designer": "relators:sds;",
                   "speaker": "relators:spk;",
                   "sponsor": "relators:spn;",
                   "stage director": "relators:sgd;",
                   "stage manager": "relators:stm;",
                   "standards body": "relators:stn;",
                   "stereotyper": "relators:str;",
                   "storyteller": "relators:stl;",
                   "supporting host": "relators:sht;",
                   "surveyor": "relators:srv;",
                   "teacher": "relators:tch;",
                   "technical director": "relators:tcd;",
                   "television director": "relators:tld;",
                   "television producer": "relators:tlp;",
                   "thesis advisor": "relators:ths;",
                   "transcriber": "relators:trc;",
                   "translator": "relators:trl;",
                   "type designer": "relators:tyd;",
                   "typographer": "relators:tyg;",
                   "university place": "relators:uvp;",
                   "videographer": "relators:vdg;",
                   "voice actor": "relators:vac;",
                   "witness": "relators:wit;",
                   "wood engraver": "relators:wde;",
                   "woodcutter": "relators:wdc;",
                   "writer of accompanying material": "relators:wam;",
                   "writer of added commentary": "relators:wac;",
                   "writer of added lyrics": "relators:wal;",
                   "writer of added text": "relators:wat;",
                   "writer of introduction": "relators:win;",
                   "writer of preface": "relators:wpr;",
                   "writer of supplementary textual content": "relators:wst;"}